# Default common config for Phpqa.
# For more options see:
#   https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml
phpcs:
    standard: Drupal
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overriden
            checkstyle: checkstyle.xml

phpmd:
    standard: ./gitlab-ci/.phpmd.xml

pdepend:
    # coverageReport: build/coverage-clover.xml

phpcpd:
    minLines: 5
    minTokens: 70

# Php file extensions to parse.
extensions:
    - php
    - inc
    - module
    - install
    - test
    - profile
    - theme
