# Default common config for Phpqa.
# For more options see:
#   https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml
phpcs:
    standard:
        - Drupal
        - DrupalPractice
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overridden
            checkstyle: checkstyle.xml
            junit: phpcs-unit.xml

phpmd:
    standard: .phpmd.xml

pdepend:
    # Must be copied in the job, see metrics:script.
    coverageReport: /tmp/coverage.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:
    # Choose phpunit to use for metrics.
    # Must be copied in the job, see metrics:script.
    junit: /tmp/junit-unit-kernel.xml
    # junit: /tmp/junit-functional.xml
    # junit: /tmp/junit-functionaljs.xml
    # Composer usage for a project can slow a lot Phpmetrics.
    # composer: ../../../../var/www/html/

phpstan:
    # https://phpstan.org/user-guide/rule-levels
    level: 5
    # https://phpstan.org/config-reference
    # https://github.com/mglaman/phpstan-drupal#usage
    standard: phpstan.neon

# Php file extensions to parse.
phpqa:
    ignoredDirs: "vendor,bootstrap,tests,.gitlab-ci"
    ignoredFiles: "Readme.md,style.css,print.css,*Test.php,RoboFile.php"
    report: true
    verbose: true
    execution: parallel
    extensions:
        - php
        - inc
        - module
        - install
        - test
        - profile
        - theme
