################################################################################
# Build template used for Build job.
################################################################################

.build_template:
  stage: build
  extends: .variables_test
  before_script:
    # Support composer mirrors and token.
    - if [ ! -z ${COMPOSER_REPO_PACKAGIST_URL} ]; then
        composer config --global repo.packagist composer ${COMPOSER_REPO_PACKAGIST_URL};
      fi
    - if [ ! -z "${COMPOSER_GITHUB_OAUTH_TOKEN}" ]; then
        composer config -g github-oauth.github.com ${COMPOSER_GITHUB_OAUTH_TOKEN};
      fi
    # Support Yarn registry mirror.
    - if [ ! -z "${YARN_REGISTRY}" ]; then
        yarn config set registry ${YARN_REGISTRY};
      fi
    - |
      # Add a ssh build key if there is a variable CI_BUILD_KEY.
      if [ ! -z "${CI_BUILD_KEY}" ]; then
        mkdir -p ~/.ssh && chmod 700 ~/.ssh;
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config;
        echo -e "${CI_BUILD_KEY}" > ~/.ssh/id_rsa;
        chmod 400 ~/.ssh/id_rsa;
      fi
  after_script:
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    # Call any extra build script from ./.gitlab-ci/scripts/build.php
    - robo ci:build
    - robo ci:prepare
  # On build we cache the composer and web folders to speed up the tests.
  cache:
    key: "drupal-${CI_COMMIT_REF_NAME}"
    paths:
      - vendor
      - web
  artifacts:
    expire_in: 1 week
    paths:
      # Build files for next steps and deploy/release.
      - vendor
      - web
      - composer.json
      - composer.lock
      # Files from this project.
      - RoboFile.php
      - .gitlab-ci
      # Deprecated Drupal composer project template.
      - drush
      - scripts
      - load.environment.php
